### ISSUE TITLE
[Bug] Deutexrium is non-functional since 36037

### ISSUE THREAD

**Issue by F0bes** [portasynthinca3/deutexrium#1]
Hi there, I've managed to bisect this issue to commit [#36037](https://github.com/portasynthinca3/deutexrium/commit/36037c96c761a5b2266c89430f3cfe19f2b42052)

```
03:08:32.994 [info]  channel-XYZ server: loading
 
03:08:32.994 [info]  channel-XYZ server: creating new meta
 
03:08:32.995 [error] Task #PID<0.704.0> started from #PID<0.675.0> terminating
** (stop) exited in: GenServer.call({:via, Registry, {Registry.Server, {:channel, {XYZ, ABC}}}}, {:generate, :neutral, nil}, 15000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.13.4) lib/gen_server.ex:1019: GenServer.call/3
    (deutexrium 1.3.3) lib/deutexrium.ex:69: Deutexrium.handle_event/1
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<7.75347062/0 in Deutexrium.start_link/1>
    Args: []
```
This is the result whenever a message is received. Thanks.

**Comment by portasynthinca3** [comment]
Interesting. I will take a look at it, thanks for the report

**Comment by portasynthinca3** [comment]
Is it possible that access permissions for the parent directory and/or the possibly existing `meta_` file are set up incorrectly? I'm able to recreate this issue when artificially restricting my access to an existing `meta_` file. Judging by the code, that's the only possible reason a channel GenServer could fail right after or during startup, causing the subsequent immediate call to the just-crashed server to fail too:
https://github.com/portasynthinca3/deutexrium/blob/36037c96c761a5b2266c89430f3cfe19f2b42052/lib/deutexrium/server/channel.ex#L53-L76

The crash itself is not logged because this process is out of any supervisor's field of vision by design.

**Comment by F0bes** [comment]
I usually run the bot as a systemd system job (That way it just runs on my raspberry pi automatically).
I've given the /var/deutex_data (and the meta_ files) full permissions to every user, I've given the folder where I execute it full permissions, and I've ran it as the root user. I still face the same issue unfortunately.
